#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Chạy lint-staged
npx lint-staged

# Kiểm tra mã trạng thái
if [ $? -ne 0 ]; then
  echo "🚫 Commit failed due to linting errors."
  exit 1
else
  echo "✅ Commit successful!"
fi
